### ISSUE TITLE
fring argument

### ISSUE THREAD

**Issue by Anusreess** [James-QiuHaoran/hgfrr#4]
app_eth eval_client eval_server. what is the use of this command how it works
![WhatsApp Image 2021-04-12 at 10 39 31](https://user-images.githubusercontent.com/57307829/114348272-f0ecbd80-9b83-11eb-88fe-2e367a454ccf.jpeg)

**Comment by James-QiuHaoran** [comment]
This command will create a simulated network environment, which is a hierarchical overlay network. As shown in the usage, you need to provide `ip_addr port_num id num_nodes_in_dist num_cnodes_in_dist num_nodes_in_city num_cnodes_in_city num_nodes_in_state num_cnodes_in_state num_nodes_in_country num_cnodes_in_country num_nodes_in_continent num_cnodes_in_continent num_continents starting_port_num start_time`.

You can refer to the examples here: https://github.com/James-QiuHaoran/structured-p2p-overlay-network/tree/master/libgfrp2p/test

**Comment by Anusreess** [comment]
How to communicate with two devices, docker containers

**Comment by James-QiuHaoran** [comment]
It's a simulated overlay network so currently, it's a client-server model simulating an overlay network. You can refer to https://github.com/James-QiuHaoran/structured-p2p-overlay-network/tree/master/libgfrp2p/docker for creating client-server docker evaluation.
