### ISSUE TITLE
Hgfr.txt is not found in docker

### ISSUE THREAD

**Issue by thoufeeqmaheen** [James-QiuHaoran/hgfrr#5]
We executed the shell programs in docker but when we try to execute eval.sh we found some error the main one is its calling a file named hgfr*.tex but it's not fond .can u help us to find it . And how can we implement a communication between server and client with docker.

How we genarate a hgfr.txt 
![IMG_20210506_130612](https://user-images.githubusercontent.com/83756157/117269629-14024880-ae76-11eb-8998-b91b0636c40f.jpg)
![IMG_20210506_140911](https://user-images.githubusercontent.com/83756157/117269652-195f9300-ae76-11eb-926c-479ec3d45fff.jpg)

**Comment by James-QiuHaoran** [comment]
Could you please describe the process, i.e., what are the commands you ran? And what's the input/output? What are the files under the generated 'log/' directory?

**Comment by thoufeeqmaheen** [comment]
sir 
we created 3 docker environments in docker (sever ,client and another one ). we run the command
![WhatsApp Image 2021-05-07 at 12 44 29 PM (1)](https://user-images.githubusercontent.com/83756157/117412478-76b91a00-af32-11eb-91a2-f21beb23edcf.jpeg)
![WhatsApp Image 2021-05-07 at 12 44 29 PM](https://user-images.githubusercontent.com/83756157/117412523-833d7280-af32-11eb-97b8-ff27be336cbe.jpeg)
![WhatsApp Image 2021-05-07 at 12 44 28 PM (2)](https://user-images.githubusercontent.com/83756157/117412590-93ede880-af32-11eb-82da-351c9b8c638f.jpeg)
![WhatsApp Image 2021-05-07 at 12 44 28 PM (3)](https://user-images.githubusercontent.com/83756157/117412599-95b7ac00-af32-11eb-9261-8994867add73.jpeg)
![WhatsApp Image 2021-05-07 at 12 44 28 PM (4)](https://user-images.githubusercontent.com/83756157/117412605-96504280-af32-11eb-9add-a830e5347a99.jpeg)


we run this in client container 
first we run this command 
 ./bootstrap.shand 

![WhatsApp Image 2021-05-07 at 12 44 27 PM (1)](https://user-images.githubusercontent.com/83756157/117412668-a9fba900-af32-11eb-8d16-56d1d9879a7c.jpeg)

we get a log  named
2021-05-07-06-17-36

then we run the 
./eval.sh 10
the input is 10
![WhatsApp Image 2021-05-07 at 12 44 27 PM](https://user-images.githubusercontent.com/83756157/117412737-c0096980-af32-11eb-8653-07212032e0d3.jpeg)



am attaching the out puts we get with it 
when we run the second command we get also a error message 
./eval.sh: line 38: bc: command not found

.
if u don't mind can u tell the steps we need to follow to run it in correct way 
i know  you rare a bc person .can u help us 

the commands we need to use in odder  
and in proper way

**Comment by jitaogithub** [comment]
As the output shows, your system lacks the `bc` program. You can find guidelines to install it with an easy search.

**Comment by thoufeeqmaheen** [comment]
sir we created 3 docker environments in docker (sever ,client and another
one ). we run the command
./bootstrap.sh
and
ve get a log file in log
2021-05-07-06-17-36
