### ISSUE TITLE
how to use the command #deploy.sh

### ISSUE THREAD

**Issue by thoufeeqmaheen** [James-QiuHaoran/hgfrr#8]
we run the command 
deploy.sh 180

but we get some error message 
am attaching the screenshot with this 

can u tell me the steps we follow to use it in the correct way and use of it 
![f2a369ce-27ac-4558-8fc2-5eb7c3736f29](https://user-images.githubusercontent.com/83756157/117831489-3d660e80-b292-11eb-9d37-86d3dcdfb4ee.jpg)

**Comment by James-QiuHaoran** [comment]
Try to install Docker and then run the same command.

**Comment by thoufeeqmaheen** [comment]
install in where in the docker container
